// "Use strict"; // use all js code as newer version

// // alert(3+3) //we are using nodejs , not browser
// let age=3//number
// let name="aniket"// string
// let isloggedin= false //boolean


// // number 2 to 53
// // big int used for large values
// // string " "
// // boolean:-true or false
// // null:-standalone value (empty)
// // undefined:-value is not assigned
// // symbol:-used to find uniqueness we will find in react


// // Objects

// console.log(typeof null);
// console.log(typeof undefined);

// const foo=1;
// const result=foo+"2"
// // console.log(result)
// const place="aniket"
// const batao="place"+1
// console.log(batao ,typeof(batao))
// let valueinNumber=Number(place)
// console.log(typeof(valueinNumber))
// console.log(valueinNumber)

// NaN Stands for Not a number
// js convert 33abc to number but actually it is not complete number so when printing it , it will show NaN.


// console.log(foo)
// js is weakly typed language , it allows type conversion easily.

// 33 => 33
// 33abc => NaN Not a Number
// Aniket => NaN
// Undefined =>NaN
// Null => 0
// True => 1
// False =>0

let isValueloggedIn ="aniket";
let boolean = Boolean(isValueloggedIn)

// 1 =>true ; 0 =>false
// 1 =>true ; 0 =>false
// "aniket" =>true
// " " =>false

console.log(boolean)


// let score=null

// let valueinNumber=Number(score)

// console.log(typeof valueinNumber)
// console.log(valueinNumber)

let value=null

let valueinNumber=Number(value)

console.log(typeof valueinNumber)
console.log(valueinNumber)






